language: java

sudo: false

jdk:
  - oraclejdk14

cache:
  directories:
    - .autoconf
    - $HOME/.m2

notifications:
  email:
    recipients:
      - vladislav.96@mail.ru
    on_success: never
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="e877e892-5d50-4307-9f67-9e3c01142090"

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres